on: [issue_comment]
name: PR Commands
jobs:
  commander:
    name: Check for commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        env:
          SHA: '${{env.parentSHA}}'
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/scripts/ga-commander.js')
            await script({github, context, core})
